<?php

/**
 * Implements hook_page_top().
 */
function firstmodule_page_top() {
  // Showing the message at the top of the page
  \Drupal::messenger()->addStatus('Hello world!');
}

/**
 * Implements hook_entity_field_access()
 * @param \Drupal\Core\Field\FieldDefinitionInterface $field_definition
 * @param \Drupal\Core\Session\AccountInterface $account
 * @return \Drupal\Core\Access\AccessResult|\Drupal\Core\Access\AccessResultAllowed|\Drupal\Core\Access\AccessResultNeutral
 */
function firstmodule_entity_field_access($operation, \Drupal\Core\Field\FieldDefinitionInterface $field_definition, \Drupal\Core\Session\AccountInterface $account) {
  $field_name = $field_definition->getName();
  if ($field_name === 'promote' || $field_name === 'sticky' ) {
    $can_promote_content_nodes = $account->hasPermission('can promote nodes');
    return Drupal\Core\Access\AccessResult::allowedIf($can_promote_content_nodes);
  }
  return \Drupal\Core\Access\AccessResult::neutral();
}
